### ISSUE TITLE
Basic test pipeline fail on  task 'os_common_user_check' when `user.pasword` var not exist

### ISSUE THREAD

**Issue by shmii** [shmii/os_common#15]
Basic test pipeline fail on task `os_common_user_check` when `user.pasword` not exist 

This appends since update my test environment from `ansible [core 2.16.3]` to `ansible [core 2.17.0]`

```
$ ansible --version
ansible [core 2.17.0]
  config file = None
  configured module search path = ['/home/thomas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/thomas/.local/lib/python3.12/site-packages/ansible
  ansible collection location = /home/thomas/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/thomas/.local/bin/ansible
  python version = 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```
The bug is in this code (and it's require a more global check to verify similar cases) : 

```
- name: "OS Common - Users - User - Check : {{ user.name | default('') }}"
  ansible.builtin.user:
    name: "{{ user.name }}"
    password: "{{ user.password | password_hash('sha512', 'FIXEDSALT') | default(omit) }}"
```

Chaining filters like this : `password: "{{ user.password | password_hash('sha512', 'FIXEDSALT') | default(omit) }}"`, not working anymore.

**Comment by shmii** [comment]
This can be patched with the usage of `if ... else` like this :

```
- name: "OS Common - Users - User - Check : {{ user.name | default('') }}"
  ansible.builtin.user:
    name: "{{ user.name }}"
    password: "{{ user.password | password_hash('sha512','FIXEDSALT') if (user.password is defined) else omit}}"
```


-- 
_Tips Source : (https://stackoverflow.com/questions/65999224/chaining-omit-with-password-hash-filter)_
